### ISSUE TITLE
Cocoapods error

### ISSUE THREAD

**Issue by segunlee** [jianstm/Schedule#12]
Installing Schedule (0.0.4)
....
warning: Could not find remote branch 0.0.4 to clone.
fatal: Remote branch 0.0.4 not found in upstream origin

**Comment by jianstm** [comment]
Hi, @segunlee , try to update your local pod repo with `pod repo update`,  or update Schedule only with `pod update Schedule`. Schedule just release 0.1.0, which is a a very stable version. All versions before 0.0.9 were obsoleted due to some embarrassing bugs. 

Sorry for confusing you. But try 0.1.0! It's more amazing~

**Comment by segunlee** [comment]
my mistake, thx  :-)
