### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ApolloZhu** [jianstm/Schedule#31]
I noticed this library is leaking `RunLoopTask`:

![image](https://user-images.githubusercontent.com/10842684/52907092-3291b000-3228-11e9-9791-54e727db64b9.png)

and can be reproduced with this trivial macOS example:

```swift
class ViewController: NSViewController {
    var task: Task?
    @IBAction func onButtonPress(_ sender: Any) {
        task = Plan.after(Interval(seconds: 2)).do {
            print("Hi")
        }
    }
}
```

**Comment by jianstm** [comment]
Hi, @ApolloZhu , thanks for your feedback. I just pushed a [commit](https://github.com/jianstm/Schedule/commit/cde488374320a1e1c766306348bfcbe9d066bad8) and hope it will fix the problem.

**Comment by jianstm** [comment]
I'm working on 2.x branch now, and hopefully, I will release 2.0 with this today!

**Comment by ApolloZhu** [comment]
This fix requires manually invoke task.cancel(). Is that intended behavior?

**Comment by jianstm** [comment]
...
Yes. I thought you were talking about the memory leak caused by an object reference being caught by a closure.
Yes, if a task is no longer being used, you should call its `cancel` method to release it. I wrote it [here](https://github.com/jianstm/Schedule#management)). Sorry, my intention is to make it consistent with the timer experience(`timer.invalidate()`), but I also realized that it seems a bit misleading to users. 
I am doing some refactoring now and may redesign this part of the api.

**Comment by ApolloZhu** [comment]
Thanks for the explanation and sorry for not providing enough context in the previous comment.
